### ISSUE TITLE
Light-dependent resistance get value probelm

### ISSUE THREAD

**Issue by sebillen** [ftrobopy/ftrobopy_server#4]
Hi,
I try to get LDR value by following example on TXTwithPython.pdf page 16-17.
What ever I do, value is always -1, do you have a idea?

**Comment by ftrobopy** [comment]
Should work now.
This was a bug and has been fixed in version 0.9.11

**Comment by sebillen** [comment]
I download last version and replace ftrobopy_server on Txt.
now I get errors when I execute script
----
import ftrobopy
txt = ftrobopy.ftrobopy('192.168.7.2', 65000)  # Connected by USB cable
R = txt.resistor(3)      # Here input 1 is 1 
ohm = 0                 # Initialize to non­existing value
while 1:                 # Start endless loop
   txt.updateWait()
   newohm = R.value()
   if newohm != ohm:  
      print("Current resistance is {:d} Ohm     \r".format(newohm), end='\r') 
      ohm = newohm
   if newohm == 15000:
      break 
----
PS C:\Users\Sebillen\source\Repos\FischerTechnikDemo\TxTPython> py .\LDRreaderOO.py
Connected to  TX2013 firmware version 4.7.0
Received data size ( 0 ) does not match length of format string ( 80 )
Connection to TXT aborted
Traceback (most recent call last):
  File "C:\Users\Sebillen\source\Repos\FischerTechnikDemo\TxTPython\LDRreaderOO.py", line 15, in <module>
    R = txt.resistor(3)      # Here input 1 is 1
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\ftrobopy.py", line 3166, in resistor
    self.updateConfig(ext)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\ftrobopy.py", line 785, in updateConfig
    res = self._sock.send(buf)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
PS C:\Users\Sebillen\source\Repos\FischerTechnikDemo\TxTPython>
PS C:\Users\Sebillen\source\Repos\FischerTechnikDemo\TxTPython> py .\LDRreaderOO.py
Connected to  TX2013 firmware version 4.7.0
Received data size ( 0 ) does not match length of format string ( 80 )
Connection to TXT aborted
Traceback (most recent call last):
  File "C:\Users\Sebillen\source\Repos\FischerTechnikDemo\TxTPython\LDRreaderOO.py", line 15, in <module>
    R = txt.resistor(3)      # Here input 1 is 1
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\ftrobopy.py", line 3166, in resistor
    self.updateConfig(ext)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\ftrobopy.py", line 785, in updateConfig
    res = self._sock.send(buf)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

----
Error on Txt:
ft@txt40-uBcx:~/workspaces$ ./ftrobopy_server
ftrobopy and ROBOPro Online Server, version 0.9.11, (c) 2022 by Torsten Stuehn
press return to close ftrobopy_server...
got: query status
got: start online
I2C: thread started
I2C: socket opened ... waiting for connection on port 65002
I2C: connection established ... (i2c functionality not yet implemented)
I2C: data received over socket is invalid
I2C: 0 bytes received:
I2C: received invalid i2c command
I2C: unknown command or command not supported
I2C: m_id=0
I2C0 bytes received:
I2C:  --> sending back 4 bytes, m_resp_id=0x1020304

I2C: data received over socket is invalid
I2C: 0 bytes received:
I2C: received invalid i2c command
I2C: unknown command or command not supported
I2C: m_id=0
I2C0 bytes received:
I2C:  --> sending back 4 bytes, m_resp_id=0x1020304

**Comment by ftrobopy** [comment]
Yes, you are right, there still seems to be a problem with I2C (which is anyhow not really supported yet, but is needed for the Communication with ROBOPro).
I will have a look into that

**Comment by sebillen** [comment]
Hi, 
Have you any news?

**Comment by ftrobopy** [comment]
I uploaded version 0.9.12 with disabled i2c.
ftrobopy_server should work again, including LDR.

**Comment by sebillen** [comment]
Thanks, working fine, continue my tests :)
